name: 'Test And Build'

on:
  push:
    branches:
    - main

jobs:
  test-ubuntu:
    strategy:
      fail-fast: false
    name: 'Test Ubuntu image'
    concurrency: 
      group: test_ubuntu_group
      cancel-in-progress: true
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Dockerfile lint
      run: docker run --rm -i -v "$PWD:/data:ro" -w /data hadolint/hadolint hadolint Dockerfile # docker run --rm -i hadolint/hadolint < Dockerfile
  
  test-alpine:
    strategy:
      fail-fast: false
    name: 'Test Alpine image'
    concurrency: 
      group: test_alpine_group
      cancel-in-progress: true
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Dockerfile lint
      run: docker run --rm -i -v "$PWD:/data:ro" -w /data hadolint/hadolint hadolint Dockerfile.alpine

  build-ubuntu:
    needs: test-ubuntu
    strategy:
      fail-fast: false
    name: 'Build and push ubuntu image'
    concurrency: 
      group: build_ubuntu_group
      cancel-in-progress: true
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ncsystems/kook
      
    - name: Build and push Docker ubuntu image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ncsystems/kook:ubuntu
        labels: ${{ steps.meta.outputs.labels }}

  build-alpine:
    needs: test-alpine
    strategy:
      fail-fast: false
    name: 'Build and push alpine image'
    concurrency: 
      group: build_alpine_group
      cancel-in-progress: true
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ncsystems/kook
      
    - name: Build and push Docker ubuntu image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile.alpine
        push: true
        tags: |
          ncsystems/kook:alpine
        labels: ${{ steps.meta.outputs.labels }}