name: 'Test And Build'

on:
  push:
    branches:
    - main

jobs:
  test:
    strategy:
      fail-fast: false
    name: 'Test'
    concurrency: 
      group: test_group
      cancel-in-progress: true
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker lint
      run: docker run --rm -i -v "$PWD:/data:ro" -w /data hadolint/hadolint hadolint Dockerfile # docker run --rm -i hadolint/hadolint < Dockerfile

  build:
    needs: test
    strategy:
      fail-fast: false
    name: 'Build'
    concurrency: 
      group: build_group
      cancel-in-progress: true
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker build
      run: docker build -t kook:latest . --no-cache