name: 'Test And Build'

on:
  push:
    branches:
    - main

jobs:
  test:
    strategy:
      fail-fast: false
    name: 'Test'
    concurrency: 
      group: test_group
      cancel-in-progress: true
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker lint
      run: docker run --rm -i -v "$PWD:/data:ro" -w /data hadolint/hadolint hadolint Dockerfile # docker run --rm -i hadolint/hadolint < Dockerfile

  build:
    needs: test
    strategy:
      fail-fast: false
    name: 'Build'
    concurrency: 
      group: build_group
      cancel-in-progress: true
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the fresh image
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ncsystems/kook
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ncsystems/kook:latest
        labels: ${{ steps.meta.outputs.labels }}